import Head from "next/head";
import Image from "next/image";
import Layout from "../components/layout";
<<<<<<< HEAD
import Hero from "../components/home/hero";

=======
>>>>>>> 326be14c30291fc5012133fa55e3c922fe63cc79

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>PortFolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<<<<<<< HEAD
      <section className="flex min-h-screen flex-col items-center justify-center text-gray-600 body-font">
        <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
          <Hero />
          
        </div>
      </section>
=======

      <h1 className="text-3xl font-bold underline">TEST</h1>
>>>>>>> 326be14c30291fc5012133fa55e3c922fe63cc79
    </Layout>
  );
}
