import Layout from "../components/layout";
import Head from "next/head";
import { GetStaticPropsContext } from "next";
import {TOKEN, DATABASE_ID} from "../config/index"
import ProjectItem from "../components/projects/project_item";

// type FetchTypes={
//   projects : object,
//   properties : object
// }

export default function Projects({projects}:any) {

  return (
      <Layout>
        <div className="flex flex-col items-center justify-center min-h-screen px-5 py-24 mb-10 px-6">
          <Head>
            <title>PortFolio</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            
          </Head>
          <h1 className="text-4xl font-bold sm:text-6xl">
            총 프로젝트 : 
            <span className="pl-4 text-blue-500">{projects.results.length}</span>
            </h1>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 xs:w-full">
            {projects.results.map((aProject:any)=>(
              <ProjectItem key={aProject.id} data={aProject}/>
            ))}
          </div>
        </div>


      </Layout>
  );
}

//빌드 타임에 호출
export async function getStaticProps() {

  const options = {
    method: 'POST',
    headers: {
      Accept: 'application/json',
      'Notion-Version': '2022-06-28',
      'Content-Type': 'application/json',
      Authorization: `Bearer ${TOKEN}`
    },
    body: JSON.stringify({
      sorts:[{
        "property":"이름",
        "direction":"ascending"
      }],
      page_size: 100})
  };
  
  const res = await fetch(`https://api.notion.com/v1/databases/${DATABASE_ID}/query`, options)

  const projects = await res.json()


  const projectNames = projects.results.map((project:any)=>(
    project.properties.이름.title[0].plain_text
  ))


  return {
    props: {projects}
  }
}
